// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createNoopSupabaseAdminClient() {
  const makeResult = <T>(data: T, error?: { message: string } | null) => ({ data, error: error ?? null });

  return {
    auth: {
      getSession: async () => makeResult({ session: null }),
      getClaims: async () => makeResult({ claims: null }),
    },
    from: () => ({
      select: () => ({
        eq: () => ({
          maybeSingle: async () => makeResult(null),
          order: () => ({
            maybeSingle: async () => makeResult(null),
          }),
        }),
      }),
      insert: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
      update: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
      delete: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
    }),
    storage: {
      from: () => ({
        upload: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
        createSignedUrl: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
      }),
    },
    rpc: async () => makeResult(null, { message: 'Supabase is not configured. Add the env vars in Vercel.' }),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL || '';
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(
      `[Supabase] Missing env var(s): ${missing.join(', ')}. Continuing in safe fallback mode so Vercel does not crash.`,
    );
    return createNoopSupabaseAdminClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
